pool:
  name: Default

variables:
  solution: './ClientLibrary/Samples/ClientSamples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
- task: Docker@2
  inputs:
    containerRegistry: 'my-public-docker-hub'
    repository: 'sample'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'